/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PoleFormateurRouteImport } from './routes/pole-formateur'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppEspaceIndexRouteImport } from './routes/_app.espace.index'
import { Route as AppEspaceProfilRouteImport } from './routes/_app.espace.profil'
import { Route as CatalogueCategoryIndexRouteImport } from './routes/catalogue.$category.index'
import { Route as CatalogueCategorySlugRouteImport } from './routes/catalogue.$category.$slug'
import { Route as AppEspaceDossiersNewRouteImport } from './routes/_app.espace.dossiers.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PoleFormateurRoute = PoleFormateurRouteImport.update({
  id: '/pole-formateur',
  path: '/pole-formateur',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppEspaceIndexRoute = AppEspaceIndexRouteImport.update({
  id: '/espace/',
  path: '/espace/',
  getParentRoute: () => AppRoute,
} as any)
const AppEspaceProfilRoute = AppEspaceProfilRouteImport.update({
  id: '/espace/profil',
  path: '/espace/profil',
  getParentRoute: () => AppRoute,
} as any)
const CatalogueCategoryIndexRoute = CatalogueCategoryIndexRouteImport.update({
  id: '/catalogue/$category/',
  path: '/catalogue/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueCategorySlugRoute = CatalogueCategorySlugRouteImport.update({
  id: '/catalogue/$category/$slug',
  path: '/catalogue/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEspaceDossiersNewRoute = AppEspaceDossiersNewRouteImport.update({
  id: '/espace/dossiers/new',
  path: '/espace/dossiers/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pole-formateur': typeof PoleFormateurRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/espace/profil': typeof AppEspaceProfilRoute
  '/catalogue/$category/$slug': typeof CatalogueCategorySlugRoute
  '/admin/': typeof AppAdminIndexRoute
  '/espace/': typeof AppEspaceIndexRoute
  '/catalogue/$category/': typeof CatalogueCategoryIndexRoute
  '/espace/dossiers/new': typeof AppEspaceDossiersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pole-formateur': typeof PoleFormateurRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/espace/profil': typeof AppEspaceProfilRoute
  '/catalogue/$category/$slug': typeof CatalogueCategorySlugRoute
  '/admin': typeof AppAdminIndexRoute
  '/espace': typeof AppEspaceIndexRoute
  '/catalogue/$category': typeof CatalogueCategoryIndexRoute
  '/espace/dossiers/new': typeof AppEspaceDossiersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pole-formateur': typeof PoleFormateurRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/_app/espace/profil': typeof AppEspaceProfilRoute
  '/catalogue/$category/$slug': typeof CatalogueCategorySlugRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/espace/': typeof AppEspaceIndexRoute
  '/catalogue/$category/': typeof CatalogueCategoryIndexRoute
  '/_app/espace/dossiers/new': typeof AppEspaceDossiersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/pole-formateur'
    | '/catalogue/'
    | '/espace/profil'
    | '/catalogue/$category/$slug'
    | '/admin/'
    | '/espace/'
    | '/catalogue/$category/'
    | '/espace/dossiers/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/pole-formateur'
    | '/catalogue'
    | '/espace/profil'
    | '/catalogue/$category/$slug'
    | '/admin'
    | '/espace'
    | '/catalogue/$category'
    | '/espace/dossiers/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/pole-formateur'
    | '/catalogue/'
    | '/_app/espace/profil'
    | '/catalogue/$category/$slug'
    | '/_app/admin/'
    | '/_app/espace/'
    | '/catalogue/$category/'
    | '/_app/espace/dossiers/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PoleFormateurRoute: typeof PoleFormateurRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
  CatalogueCategorySlugRoute: typeof CatalogueCategorySlugRoute
  CatalogueCategoryIndexRoute: typeof CatalogueCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pole-formateur': {
      id: '/pole-formateur'
      path: '/pole-formateur'
      fullPath: '/pole-formateur'
      preLoaderRoute: typeof PoleFormateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/espace/': {
      id: '/_app/espace/'
      path: '/espace'
      fullPath: '/espace/'
      preLoaderRoute: typeof AppEspaceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/espace/profil': {
      id: '/_app/espace/profil'
      path: '/espace/profil'
      fullPath: '/espace/profil'
      preLoaderRoute: typeof AppEspaceProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/catalogue/$category/': {
      id: '/catalogue/$category/'
      path: '/catalogue/$category'
      fullPath: '/catalogue/$category/'
      preLoaderRoute: typeof CatalogueCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/$category/$slug': {
      id: '/catalogue/$category/$slug'
      path: '/catalogue/$category/$slug'
      fullPath: '/catalogue/$category/$slug'
      preLoaderRoute: typeof CatalogueCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/espace/dossiers/new': {
      id: '/_app/espace/dossiers/new'
      path: '/espace/dossiers/new'
      fullPath: '/espace/dossiers/new'
      preLoaderRoute: typeof AppEspaceDossiersNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEspaceProfilRoute: typeof AppEspaceProfilRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppEspaceIndexRoute: typeof AppEspaceIndexRoute
  AppEspaceDossiersNewRoute: typeof AppEspaceDossiersNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEspaceProfilRoute: AppEspaceProfilRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppEspaceIndexRoute: AppEspaceIndexRoute,
  AppEspaceDossiersNewRoute: AppEspaceDossiersNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PoleFormateurRoute: PoleFormateurRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
  CatalogueCategorySlugRoute: CatalogueCategorySlugRoute,
  CatalogueCategoryIndexRoute: CatalogueCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
